using System;
using System.Collections.Generic;

namespace Italbytz.EA.SearchSpace;

/// <summary>
///     Represents a polynomial expression in genetic programming for search
///     algorithms.
/// </summary>
/// <typeparam name="TCategory">The category type used in the polynomial.</typeparam>
public interface IPolynomial<TCategory> : ICloneable
{
    /// <summary>
    ///     Gets or sets the list of monomials that constitute this polynomial.
    /// </summary>
    public List<IMonomial<TCategory>> Monomials { get; set; }

    public double[] Evaluate(TCategory[] input);
    
    /// <summary>
    ///     Gets or sets the predictions generated by this polynomial.
    /// </summary>
    public float[][] Predictions { get; set; }

    /// <summary>
    ///     Gets the size of the polynomial, typically the number of different
    ///     literals.
    /// </summary>
    int Size { get; }

    /// <summary>
    ///     Retrieves a random monomial from the available search space.
    /// </summary>
    /// <returns>A random monomial instance.</returns>
    IMonomial<TCategory> GetRandomMonomial();

    /// <summary>
    ///     Updates the prediction values based on the current state of the polynomial.
    /// </summary>
    void UpdatePredictions();

    /// <summary>
    ///     Gets all literals used within this polynomial.
    /// </summary>
    /// <returns>A list of all literals contained in the polynomial.</returns>
    List<ILiteral<TCategory>> GetAllLiterals();
}